name: R13Y

on:
  push:
    branches: [ main ]
  schedule:
  - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    name: "check: Reproducibility fuzzing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          install_url: https://releases.nixos.org/nix/nix-2.11.1/install
          extra_nix_config: |
            experimental-features = nix-command flakes recursive-nix ca-derivations
      - name: Install tools
        run: |
          sudo -i nix-env -i $(nix build nixpkgs#diffoscopeMinimal nixpkgs#jq --no-link --print-out-paths)
      - name: Setup diff hook
        run: |
          cat <<EOF > diff-hook.sh
          #!/usr/bin/env bash
          exec >&2
          echo "For derivation \$3 (tmpdir = \$4):"
          exec /nix/var/nix/profiles/default/bin/diffoscope --html /tmp/report.html --text /tmp/report.txt "\$1" "\$2"
          EOF
          chmod +x diff-hook.sh && sudo mv diff-hook.sh /etc/nix/diff-hook.sh
      - name: Build world
        run: nix build .#world
      - name: Iterate and rebuild world, repeatedly
        run: |
          echo "Performing R13Y tests"
          echo "====================="
          repeats=3

          if [[ ${{ github.event_name }} == "schedule" ]]; then
            repeats=10
            echo "Nightly build; using a high repeat count: $repeats"
          elif [[ ${{ github.event_name }} == "push" ]]; then
            repeats=5
            echo "Push event; using a moderate repeat count: $repeats"
          else
            echo "WARNING: invalid event name, using low repeat count: $repeats"
          fi

          sudo mkdir /tmp/diffoscope-reports
          while read -r line; do
            attr=$(cat "result/$line")
            echo "R13Y test of $attr (repeats=$repeats)"

            # build, but don't exit on error. set -e is implied
            # https://github.community/t/github-action-terminates-on-first-non-zero-exit-code/240701
            if ! nix --option run-diff-hook true \
                     --option diff-hook /etc/nix/diff-hook.sh \
                     --option enforce-determinism true \
                     --option repeat $repeats \
                   build ".#$attr" --no-link --rebuild --keep-failed; then
              echo "Failed. Diff from 'diffoscope' below:"
              cat /tmp/report.txt
              sudo mv /tmp/report.txt  /tmp/diffoscope-reports/$attr.txt
              sudo mv /tmp/report.html /tmp/diffoscope-reports/$attr.html
            else
              sudo rm -f /tmp/report.*
            fi
          done < result/nix-refs
          echo "Done."

          # now exit _after_ we're done doing reports
          if compgen -G "/tmp/diffoscope-reports/*" >/dev/null; then
            exit 1
          fi
      - name: Upload R13Y reports
        if: failure() # only runs if previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: r13y-reports
          path: /tmp/diffoscope-reports
